Update run

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,13 +1,12 @@
-#!/bin/bash 
-
-
-#      ▇▇▇                                       ▇▇▇               ▄▇▇▇▇▇▄                 ▇▇                                    ▇▇                
-#      ▇▇        ▇                        ▇       ▇▇             ▄▇                ▇▄                        ▇▇                  ▇▇
-#      ▇▇          ▇ @M0000   ▇         ▇▇            ▄▇▄▄▄▄▄▇▄                               ▇▇ ▇▇
-#      ▇▇             ▇             ▇             ▇▇        ▄▇                            ▇▄                          ▇▇ ▇▇ ¦ Dev : @M0000
-#      ▇▇                ▇       ▇                ▇▇      ▄▇ ¦ Dev : @M0000  ▇▄                 ▇▇                 ▇▇
-#      ▇▇                   ▇▇                    ▇▇     ▄▇                                    ▇▄      ▇▇                                  ▇▇¦ Source LANA  BY @M0009
-#---------------------------------------------------------------------
+--[[
+─▄█▀█▄──▄███▄─
+▐█░██████████▌
+─██▒L    A    N    A███─
+──▀████████▀──┊@M0000
+─────▀██▀─────
+┊SASKE ‿ @M0000
+#-------------------------------------------------------------------
+]]
 cd $(cd $(dirname $0); pwd)
  
 RED='\033[0;31m'
@@ -21,17 +20,18 @@ CNIL='\033[0m'
 Version=`lsb_release -rs | cut -f1 -d"."`
 
 if [ "$Version" == "18" ];then
-echo -e "${GREEN}
-▇▇▇                                       ▇▇▇               ▄▇▇▇▇▇▄                 ▇▇                                    ▇▇                
-▇▇        ▇                        ▇       ▇▇             ▄▇                ▇▄                        ▇▇                  ▇▇
-▇▇          ▇ @M0000   ▇         ▇▇            ▄▇▄▄▄▄▄▇▄                               ▇▇ ▇▇
-▇▇             ▇             ▇             ▇▇        ▄▇                            ▇▄                          ▇▇ ▇▇ ¦ Dev : @M0000
-▇▇                ▇       ▇                ▇▇      ▄▇ ¦ Dev : @M0000  ▇▄                 ▇▇                 ▇▇
-▇▇                   ▇▇                    ▇▇     ▄▇                                    ▇▄      ▇▇                                  ▇▇¦ Source LANA  BY @M0000
-----------------------------------------------------------------------${CNIL}"
+--[[
+─▄█▀█▄──▄███▄─
+▐█░██████████▌
+─██▒L    A    N    A███─
+──▀████████▀──┊@M0000
+─────▀██▀─────
+┊SASKE ‿ @M0000
+#-------------------------------------------------------------------
+]]
 echo -e "${RED}| للاسف لايمكنك تنصيب السورس ع نظام اوبنتو {${Version}} يجب ان يكون على اصدار  اقل مثلا  ${SMAY}14 او 16
 ${CNIL}";
-echo -e "${RED}| Sorry Canot install Source on Ubuntu {${Version}} Please install system To Ubuntu ${SMAY}14 or 16 ${RED} For Run The Source LANA 
+echo -e "${RED}| Sorry Canot install Source on Ubuntu {${Version}} Please install system To Ubuntu ${SMAY}14 or 16 ${RED} For Run The Source saske 
 ${CNIL}";
 exit;
 fi
@@ -41,7 +41,7 @@ if [ ! -f "./TG" ]; then
 echo -e "${RED}
 ¦
 ¦ CAUTION:${WHITB} Your Not Dwonload TG .
-¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Source lana${CNIL} . \n
+¦ NOW I Run File ${Yellow}./run${WHITB} To install ${SMAY}Source SASKE${CNIL} . \n
 \n\n"
 chmod +x ./ins
 ./ins
@@ -70,10 +70,10 @@ sudo rm -fr ../.telegram-cli
 done
 else
 
-if ! screen -list | grep -q "lana"; then
-screen -S lana ./run R
+if ! screen -list | grep -q "saske"; then
+screen -S saske ./run R
 fi
-screen -X -S lana kill
-screen -S lana ./run R
+screen -X -S saske kill
+screen -S saske ./run R
 fi
 
